services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: vaflyaartek/backend:latest
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - ./server/.env

  frontend:
    image: vaflyaartek/frontend:latest
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./client/.env

volumes:
  pgdata: